### ISSUE TITLE
Add all missing test jobs for a push

### ISSUE THREAD

**Issue by gijsk** [mozilla/mozilla_ci_tools#326]
$ mozci-trigger -r 798b34311779 --repo-name try --existing-only
    Traceback (most recent call last):
      File "e:\mozilla-build\python\Scripts\mozci-trigger-script.py", line 9, in <module>
        load_entry_point('mozci==0.14.1.dev0', 'console_scripts', 'mozci-trigger')()
      File "build\bdist.win32\egg\mozci\scripts\trigger.py", line 197, in main
      File "build\bdist.win32\egg\mozci\scripts\trigger.py", line 137, in validate_options
    Exception: A buildername is mandatory for all modes except --coalesced. Use --buildername.

I would expect this to just start all the tests.

**Comment by armenzg** [comment]
Hi @gijsk what were you trying to do here?

For the record, we have a proof of concept here in case it makes it easier:
http://try-extender.herokuapp.com

**Comment by gijsk** [comment]
So I had a trypush: https://treeherder.mozilla.org/#/jobs?repo=try&revision=798b34311779

For some reason it only got build runs but no tests, when I originally had it pushed (via mozreview + autoland). I wanted to run all the tests for the builds that had run (but not create new tests), ie the equivalent of the trysyntax "-u all" -- but only for the builds that had been created, not for other builds (eg. android, b2g, desktop builds that hadn't been built, ...).

It looks like the try-extender app offers UI for that, but I'd have to check all the relevant checkboxes. Being able to tick the builds, or have some way of indicating that I wanted all the mochitest runs, or all the reftest variants, or... - without ticking dozens or even hundreds of checkboxes manually - would be ideal.

**Comment by armenzg** [comment]
Yes, try-extender is a POC. We are working the core components to build a difference experience.

We should help with your use case.

**Comment by armenzg** [comment]
I think we could use --fill-revision in here:
https://github.com/mozilla/mozilla_ci_tools/blob/2cc9f0b8f7cb4378c06a28df9fda45d72af1d43c/mozci/scripts/trigger.py#L264
and only trigger tests for existing builds.

Perhaps we could have a flag --trigger-only-test-jobs to make it extra obvious rather than having to use two flags (--fill-revision and --existing-only).

trigger_missing_jobs_for_revision will trigger everything rather that only test jobs for existing build jobs.
https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/mozci.py#L508

**Comment by armenzg** [comment]
@gijsk we've landed some code that fixes this:
https://github.com/mozilla/mozilla_ci_tools/commit/f8679c7e447954af2690b2c8fb53c0f1c93684da
