### ISSUE TITLE
Release the pushlog module as a Python package and depend on it

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#344]
Filed as:
https://bugzilla.mozilla.org/show_bug.cgi?id=1203621

**Comment by priyanklodha** [comment]
How should I go about this. Guide me. @adusca @armenzg

**Comment by adusca** [comment]
Hi @priyanklodha! This issue is being tracked at https://bugzilla.mozilla.org/show_bug.cgi?id=1203621

The idea is to move functions that are currently in pushlog.py into a new file (called pylib/mozhginfo) in version-control-tools (a different repo). 

You would have to submit a patch to version-control-tools with a new file containing the functions in pushlog.py and after that gets merged you should submit a patch to mozci to remove the functions here and import the ones from version-control-tools instead. We want to do this because we believe this functions would be useful for other modules besides mozci, and we want to make them more easily accessible.

Steps:
- create an account at bugzilla
- clone version-control-tools
- write a patch with the new file containing the functions (there are instructions on how to create a patch with mercurial here: https://ateam-bootcamp.readthedocs.org/en/latest/guide/development_process.html#mercurial )
- submit your patch on bug 1203621 and ask for review (probably from :armenzg or :gps)

**Comment by armenzg** [comment]
hi @priyanklodha we have someone else interested working on this.
Since I have not heard back in over a month I belive it is safe to assume that you can pick up other issues if you're still interested in contributing.

**Comment by armenzg** [comment]
@priyanklodha my apologies. I realized that collabaration could be happening outside of the actual GH issues.

Are you still interested on this issue?

**Comment by MikeLing** [comment]
Hi @armenzg and @adusca , after second thought, I would like to take this in my pocket even the convert full revision haven't been fixed. Due to our time zone is different, I would like to work on two issues at same time so I can switch to another issue when I get stuck. And I can bring my question on IRC when you online ;)

**Comment by MikeLing** [comment]
Due to those comments for another release issue about buildapi_client, I create a repo in here :) https://github.com/MikeLing/pushlog_client

**Comment by armenzg** [comment]
You can make pushlog_client a dependency for buildapi_client.

**Comment by armenzg** [comment]
I forked a mirror of version-control-tools; let's use that:
https://github.com/armenzg/version-control-tools

**Comment by MikeLing** [comment]
Hmm, I haven't understand the meaning of 'use mirror version-control-tools', could you explain more for me? What's this vct for? How to use it? Should I fork it?
Thank you.

**Comment by adusca** [comment]
Hi @MikeLing! The idea is to submit a patch to version-control-tools containing a new file called mozhginfo.py under pylib/ so everything can be kept up-to-date together (see https://bugzilla.mozilla.org/show_bug.cgi?id=1203621#c3 ). This file will have the same contents as pushlog.py, and in the future we are going to depend on it. We also want to move the tests for pushlog.py.

@armenzg Does version-control-tools accept patches from git? I see in https://github.com/mozilla/version-control-tools/pulls?utf8=%E2%9C%93&q=is%3Apr that they had 0 PRs. It looks like they only use hg patches.

**Comment by MikeLing** [comment]
@adusca Thank you ! so I should fork the version-control-tools first, then create a pushlog_client folder under pylib/ which include pushlog.py and test for it. right?

**Comment by armenzg** [comment]
@adusca would you mind looking at this class https://github.com/armenzg/version-control-tools/pull/1/files#diff-e3162bccd774442d618e5b04312c55f1R66 ?

For anyone interested we're making progress in here:
https://github.com/armenzg/version-control-tools/pull/1

**Comment by MikeLing** [comment]
Maybe we could close this issue? :)

**Comment by MikeLing** [comment]
Oh, I think maybe we need to add these code https://github.com/MikeLing/version-control-tools/commit/c46cb4b52ecc73cf209cb5b6108e86dc6d24fdb6 for this https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/sources/pushlog.py#L92 ?

I somehow miss it in last PR because I think it's good to work, but I found it's necessary for mozci_tool. :)

**Comment by armenzg** [comment]
Yes, we need to modify mozci to use the pushlog_client. Please let me know if you have questions.

**Comment by armenzg** [comment]
@MikeLing got this done!
