### ISSUE TITLE
Speed up running fill-in-a-revision

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#364]
It currently takes forever (even on dry-run mode):
> time python ~/repos/ci_tools/mozci/scripts/trigger.py --repo mozilla-beta --revision db9d3e806685 --fill-revision --dry-run
> ...
> real	1m14.079s

It will also be nice if we could make the output less verbose and give a summary at the end.

**Comment by armenzg** [comment]
F3real is interested on looking at this.

**Comment by adusca** [comment]
I think the best way to go about this is to use BBB. Not only this will make --fill-revision faster, it will make it more reliable (right now when the build job doesn't exist only the build job gets triggered by us, with BBB we can schedule the downstream jobs), and with a less verbose output.

On `trigger_missing_jobs`, after obtaining the list of jobs for the repo [1], instead of calling `trigger_range` for every job we should first filter out the jobs that already exist. This is very similar to what `find_all_jobs_by_status` [2] does, the only difference is that instead of looking for a particular status you are going to remove from your list  jobs with any status *except* coalesced. After filtering your list of buildernames you can call `buildbot_graph_builder` [3] to create a builders graph, and trigger it with `schedule_graph` [4].

After that it might be possible to further improve performance by locally caching the results of functions that we call a lot of time, but without profiling it is hard to tell.

[1] https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/mozci.py#L511
[2] https://github.com/mozilla/mozilla_ci_tools/blob/e19d95954f1b62b2000cad5dc5fb3fb040611684/mozci/query_jobs.py#L118
[3] https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/sources/buildbot_bridge.py#L117
[4] https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/ci_manager.py#L115

**Comment by armenzg** [comment]
@adusca for president! :)

@F3real it is the better way to fix this but it will take a bit of extra understanding. Let me know if you would still be interested or prefer something else.

**Comment by armenzg** [comment]
@F3real I filed https://github.com/mozilla/mozilla_ci_tools/issues/387 
Let us know there if you're still interested with this different scope.

**Comment by armenzg** [comment]
Hi @F3real are you still interested on this issue? or are you fine if we closed it?

**Comment by armenzg** [comment]
We can live without this.
