### ISSUE TITLE
Do not delete files automatically

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#382]
It seems that we automatically clean files older than 30 days [1]
This is a very low priority issue.
This was needed for pulse_actions not to store too much data on disk, however, the dynos are restarted every day and we start from a clean slate.

This became a nuissance when I was trying to work on a push older than 30 days.

Let's not delete by default, change the value to 120 days (since TH does not keep more than 4 months of data) and have a global variable if any consumer wants to change the behaviour.

11/20/2015 12:10:47 mozci DEBUG:	 Cleaning up /home/armenzg/.mozilla/mozci/builds-2015-09-15.js

[1] https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/mozci.py#L412

**Comment by xennygrimmato** [comment]
Has this been fixed already? If not, I can take care of this and create a PR.

**Comment by armenzg** [comment]
Assigned! Thanks @xennygrimmato

**Comment by xennygrimmato** [comment]
So, since we do not want to clean by default, should I just remove this line:
https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/mozci.py#L412

And insert a global `CLEANUP_DAYS` variable in:
https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/utils/transfer.py 

I will modify:
https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/utils/transfer.py#L44
with:
```
days=CLEANUP_DAYS
```
Does this look ok to you?

**Comment by armenzg** [comment]
Yes to all :)
